# Generated by Django 3.1.7 on 2021-03-17 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe_food',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('ingredience_id', models.AutoField(primary_key=True, serialize=False)),
                ('Ingredient', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=200)),
                ('measure', models.CharField(max_length=200)),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe_food')),
            ],
        ),
    ]
