# Generated by Django 3.1.7 on 2021-03-25 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20210323_1445'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredients',
        ),
    ]
